services:
  python:
    image: genjiohara/python
    container_name: newlime
    volumes:
      - ./:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    working_dir: /root/workspace
    tty: true
